package com.company.codequality.sonarautofix.model;

public enum FixType {

    REMOVE_UNUSED_IMPORT,
    REPLACE_SYSTEM_OUT,
    ADD_LOGGER_TO_EMPTY_CATCH,
    HANDLE_EMPTY_CATCH,
    STRING_BUILDER_LOOP,
    EXTRACT_CONSTANT,
    REPLACE_DEPRECATED_API,
    FIELD_TO_CONSTRUCTOR_INJECTION,
    MOVE_TO_CONFIG,
    OPTIMIZE_OBJECT_CREATION,
    REPLACE_GENERIC_EXCEPTION,
    HIDE_UTILITY_CONSTRUCTOR,
    EXTRACT_STRING_CONSTANT,
    SIMPLIFY_RETURN,
    CONVERT_TO_TRY_WITH_RESOURCES,
    OPTIONAL_IF_PRESENT,
    SPLIT_ASSIGNMENT_FROM_CONDITION,
    REMOVE_UNUSED_VARIABLE,
    REMOVE_DEAD_ASSIGNMENT,
    REMOVE_REDUNDANT_BOOLEAN,
    USE_EQUALS_FOR_STRING,
    ADD_DEFAULT_CASE,
    ANONYMOUS_TO_LAMBDA,
    LAMBDA_TO_METHOD_REFERENCE,
    FOR_TO_ENHANCED_FOR,
    NONE,
 // NEW RULES
    COLLECTION_ISEMPTY_CHECK,
    COLLECTION_NOT_EMPTY_CHECK,
    STRINGBUFFER_TO_STRINGBUILDER,
    REMOVE_EMPTY_METHOD,
    REMOVE_EMPTY_IF
    
  
}



