package com.company.codequality.sonarautofix.model;

public enum FixType {

    REMOVE_UNUSED_IMPORT,
    REPLACE_SYSTEM_OUT,
    ADD_LOGGER_TO_EMPTY_CATCH,
    HANDLE_EMPTY_CATCH,
    STRING_BUILDER_LOOP,
    EXTRACT_CONSTANT,
    REPLACE_DEPRECATED_API,
    FIELD_TO_CONSTRUCTOR_INJECTION,
    MOVE_TO_CONFIG,
    OPTIMIZE_OBJECT_CREATION,
    REPLACE_GENERIC_EXCEPTION,
    HIDE_UTILITY_CONSTRUCTOR,
    EXTRACT_STRING_CONSTANT,
    SIMPLIFY_RETURN
}