spring.application.name=sonarautofix

sonar.host.url=http://localhost:9000

sonar.token=squ_fa381febfa9addf75f99b91e1ac7b4de5b711e55

sonar.token=squ_fd5b2759d9b9bc4f9b338fc3face5c756788e5af

sonar.projectKey=sonarautofix
sonar.projectBaseDir=D:/sonarautofix/sonarautofix
project.workspace=D:/sonar-workspace
server.port=9090


sonar.profile.language=java
sonar.profile.name=AutoFix-25-Java

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.port=9090



file.path=/auth
external.config=USER_NOT_FOUND
file.path.1=/loans
file.path.2=/loans

configValue=192.168.1.10
databaseUrl=jdbc:mysql://192.168.1.50:3306/testdb
