spring.application.name=sonarautofix

# ── SonarQube ──────────────────────────────────────────────────────────────
sonar.host.url=http://localhost:9000
sonar.token=squ_9025c0cbec3c0bde15338f88dbab1c2322a8b12c

sonar.profile.language=java
sonar.profile.name=AutoFix-25-Java

# ── File Upload ─────────────────────────────────────────────────────────────
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ── Tool Paths (change these to match your machine) ─────────────────────────
# Run 'where mvn'  in cmd to find your Maven binary path
maven.path=D:/UI_Design/apache-maven-3.9.12/bin/mvn.cmd

# Run 'where git'  in cmd to find your Git binary path
git.path=C:/Program Files/Git/cmd/git.exe

# Directory where uploaded/cloned projects are extracted and scanned
workspace.path=C:/sonar-workspace/
